owner: rachellanman # Your GitHub organization or username, where this repository lives
repo: website-monitoring # The name of this repository

sites:
  - name: USDS Home page 
    url: https://www.usds.gov/
  - name: USDS Apply page
    url: https://www.usds.gov/apply
  - name: Apply page iframe
    url: https://eop-fra.secure.force.com/digitalservice/
status-website:
  baseUrl: /website-monitoring
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: USDS.gov Uptime Monitoring 
  introMessage: Status page which uses **real-time** data from our [GitHub repository](https://github.com/usds/website).
  theme: light
  navbar:
    - title: Status
      href: /website-monitoring
    - title: GitHub
      href: https://github.com/rachellanman/website-monitoring

assignees:
  - kategreenUSDS
